### ISSUE TITLE
Does not compile with nginx-1.10.3, x86_64

### ISSUE THREAD

**Issue by JanSiebert** [nginx-modules/ngx_http_hmac_secure_link_module#1]
+ Darwin 16.4.0 x86_64
 + using Clang C compiler
 + clang version: 8.0.0 (clang-800.0.42.1)
  + using threads
  + using PCRE library: /Users/me/Downloads/nginx-1.10.3/pcre-8.40
  + using OpenSSL library: /Users/me/Downloads/nginx-1.10.3/openssl-1.1.0e
  + md5: using OpenSSL library
  + sha1: using OpenSSL library
  + using system zlib library

[build.txt](https://github.com/nginx-modules/nginx-hmac-secure-link/files/807230/build.txt)

**Comment by ghost** [comment]
Also doesn't compile with 1.12.2. 

```
In function ‘ngx_http_secure_link_variable’:
error: format ‘%d’ expects argument of type ‘int *’, but argument 3 has type ‘ngx_int_t * {aka long int *}’ [-Werror=format=]
         if (sscanf((char *)p, "%d-%d-%dT%d:%d:%d%c%d:%d",

```

**Comment by ghost** [comment]
#2

**Comment by ghost** [comment]
Yeah, this still doesn't compile.
