### ISSUE TITLE
what is the unit of expire arguments?

### ISSUE THREAD

**Issue by erfantkerfan** [nginx-modules/ngx_http_hmac_secure_link_module#16]
it's not clear what is the unit of expiring in the guide

**Comment by erfantkerfan** [comment]
I looked at the source code and I think by summing it with the timestamp option it should be in **seconds**, correct?

**Comment by denji** [comment]
https://github.com/nginx-modules/ngx_http_hmac_secure_link_module/blob/0.3/ngx_http_hmac_secure_link_module.c#L361-L381
https://github.com/nginx-modules/ngx_http_hmac_secure_link_module/blob/0.3/ngx_http_hmac_secure_link_module.c#L220-L242
https://github.com/nginx-modules/ngx_http_hmac_secure_link_module/blob/0.3/ngx_http_hmac_secure_link_module.c#L20-L22
```
$secure_link_hmac_expires
```

https://github.com/nginx-modules/ngx_http_hmac_secure_link_module/blob/0.3/ngx_http_hmac_secure_link_module.c#L284
```nginx
# If the hash is incorrect then $secure_link_hmac is a NULL string.

# If the hash is correct but the link has already expired then $secure_link_hmac is "0".
# If the hash is correct and the link has not expired then $secure_link_hmac is "1".

# In production environment, we should not reveal to potential attacker
# why hmac authentication has failed
if ($secure_link_hmac != "1") {
    return 404;
}
```

**Comment by erfantkerfan** [comment]
I don't understand.
Is it in **seconds**??

**Comment by erfantkerfan** [comment]
@denji

**Comment by erfantkerfan** [comment]
FYI: it's in **seconds**
