### ISSUE TITLE
ISO 8601 timestamp format does not work anymore because the year is interpreted as a UNIX timestamp

### ISSUE THREAD

**Issue by SmaugPool** [nginx-modules/ngx_http_hmac_secure_link_module#18]
A timestamp passed in ISO 8601 format is interpreted as a UNIX timestamp because the year is accepted by the `sscanf`:

```
  160         /* Try if p is UNIX timestamp*/
  161         if (sscanf((char *)p, "%llu", &conv_timestamp) == 1) {
  162             timestamp = (time_t)conv_timestamp;
  163 
  164             ngx_log_debug1(NGX_LOG_DEBUG_HTTP, r->connection->log, 0,
  165                            "secure link timestamp: \"%T\"", timestamp);
  166         } else {
                     /* Never reached with "YYYY-MM..." format because YYYY is accepted as a %llu
```

Consequently it's not possible anymore to use ISO 8601 format since UNIX timestamp support has been added.

There is a fix in this fork:
https://github.com/neokazemi/ngx_http_hmac_secure_link_module/commit/4079f2997fb3bf645ef0c68f9c33221d82325e3e

**Comment by denji** [comment]
The new code seems to be wrong, I will edit and push master.

**Comment by SmaugPool** [comment]
Thanks, and thank you for this module, it's a very useful one.
