### ISSUE TITLE
Nginx crashes when trying to access $secure_link_token variable (bad value for hmac.len)

### ISSUE THREAD

**Issue by shmulikbb** [nginx-modules/ngx_http_hmac_secure_link_module#5]
Hi,
First of all - thank you for developing and sharing this module.

When i try to use it (nginx 1.6.2, though i don't think the version is related), nginx crashes on access to $secure_link_token variable - inside the method "ngx_encode_base64url".

After some debugging it seems that hmac.len holds a bad value after call to HMAC, probably due to the casting to u_int.

I've changed (locally) the code in the method "ngx_http_secure_link_token_variable" to this:

```
    u_int hmac_size = 0;
    HMAC(evp_md, key.data, key.len, value.data, value.len, hmac.data, &hmac_size);
    hmac.len = hmac_size;
```

Which fixes the issue.

Thanks,
Shmulik

**Comment by SmaugPool** [comment]
I also get segfaults when trying to print the `$secure_link_token` variable with nginx 1.22.

I can confirm that the work-around above still works.
