### ISSUE TITLE
show errors when i make nginx-1.10.0

### ISSUE THREAD

**Issue by haizei1024** [nginx-modules/ngx_http_hmac_secure_link_module#7]
`../module/nginx-hmac-secure-link-master/ngx_http_hmac_secure_link_module.c: In function ‘ngx_http_secure_link_variable’:
../module/nginx-hmac-secure-link-master/ngx_http_hmac_secure_link_module.c:162:32: error: format ‘%d’ expects argument of type ‘int *’, but argument 3 has type ‘ngx_int_t *’ [-Werror=format=]
                                &gmtoff_sign, &gmtoff_hour, &gmtoff_min) < 9) {
                                ^
../module/nginx-hmac-secure-link-master/ngx_http_hmac_secure_link_module.c:162:32: error: format ‘%d’ expects argument of type ‘int *’, but argument 4 has type ‘ngx_int_t *’ [-Werror=format=]
../module/nginx-hmac-secure-link-master/ngx_http_hmac_secure_link_module.c:162:32: error: format ‘%d’ expects argument of type ‘int *’, but argument 5 has type ‘ngx_int_t *’ [-Werror=format=]
../module/nginx-hmac-secure-link-master/ngx_http_hmac_secure_link_module.c:162:32: error: format ‘%d’ expects argument of type ‘int *’, but argument 6 has type ‘ngx_int_t *’ [-Werror=format=]
../module/nginx-hmac-secure-link-master/ngx_http_hmac_secure_link_module.c:162:32: error: format ‘%d’ expects argument of type ‘int *’, but argument 7 has type ‘ngx_int_t *’ [-Werror=format=]
../module/nginx-hmac-secure-link-master/ngx_http_hmac_secure_link_module.c:162:32: error: format ‘%d’ expects argument of type ‘int *’, but argument 8 has type ‘ngx_int_t *’ [-Werror=format=]
../module/nginx-hmac-secure-link-master/ngx_http_hmac_secure_link_module.c:162:32: error: format ‘%d’ expects argument of type ‘int *’, but argument 10 has type ‘ngx_int_t *’ [-Werror=format=]
../module/nginx-hmac-secure-link-master/ngx_http_hmac_secure_link_module.c:162:32: error: format ‘%d’ expects argument of type ‘int *’, but argument 11 has type ‘ngx_int_t *’ [-Werror=format=]
cc1: all warnings being treated as errors
`

**Comment by denji** [comment]
I think your GCC compiler has default flags set that switch warning to error mode.

https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html
* `-Werror, -Werror=`
  > Make all warnings into errors.

**Comment by denji** [comment]
https://github.com/nginx-modules/nginx-hmac-secure-link/commit/ac9bd5a98be87bf5cf95f8efb9f36803e47bca2f
