### ISSUE TITLE
Compile Crash

### ISSUE THREAD

**Issue by MikaTake** [nginx-modules/ngx_http_hmac_secure_link_module#8]
./configure -- with-compat --add-dynamic-module=/opt/nginx-hmac-secure-link

`cc -c -fPIC -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g  -I src/core -I src/event -I src/event/modules -I src/os/unix -I objs -I src/http -I src/http/modules \
        -o objs/addon/nginx-hmac-secure-link/ngx_http_hmac_secure_link_module.o \
        /opt/nginx-hmac-secure-link/ngx_http_hmac_secure_link_module.c
/opt/nginx-hmac-secure-link/ngx_http_hmac_secure_link_module.c: In function ‘ngx_http_secure_link_variable’:
/opt/nginx-hmac-secure-link/ngx_http_hmac_secure_link_module.c:127:5: error: unknown type name ‘int_t’; did you mean ‘int8_t’?
     int_t                         year, month, mday, hour, min, sec, gmtoff_hour, gmtoff_min;
     ^~~~~
     int8_t
make[1]: *** [objs/Makefile:1220: objs/addon/nginx-hmac-secure-link/ngx_http_hmac_secure_link_module.o] Error 1`

**Comment by denji** [comment]
Try this revision https://github.com/nginx-modules/nginx-hmac-secure-link/archive/a6e07b67e6cc5c80820cce4863e42abf0c080377.tar.gz

**Comment by denji** [comment]
Try this revision https://github.com/nginx-modules/nginx-hmac-secure-link/archive/2321bfd.tar.gz

**Comment by denji** [comment]
https://github.com/nginx-modules/ngx_http_hmac_secure_link_module/releases/tag/0.2
